version: '3'
services:
  worker:
    build:
        context: ./worker
    entrypoint: ["python", "-m", "task.main"]
    environment:
      - REDIS_HOST=redis # put the docker-compose service name
      - REDIS_PORT=4667
      - REDIS_CHANNEL=the_channel
    networks:
      - pubsub-network
    depends_on:
      - redis

  redis:
    image: redis:alpine3.10
    command: ["redis-server", "--port", "4667"]
    networks:
      - pubsub-network

networks:
    pubsub-network:
